repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: name-tests-test
    args: ['--django']
  - id: detect-private-key
  - id: check-ast
  - id: double-quote-string-fixer
  - id: no-commit-to-branch
    args: [--branch, master]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.4.0
  hooks:
  - id: reorder-python-imports

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
    - id: flake8

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v4.1.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    -   id: mypy
        additional_dependencies:
          - types-requests==2.25.0
