repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: name-tests-test
    args: ['--django']
  - id: detect-private-key
  - id: check-ast
  - id: double-quote-string-fixer
  - id: no-commit-to-branch
    args: [--branch, master]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.6
  hooks:
  - id: reorder-python-imports

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v3.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
