version: "3.7"

services:
  database:
    image: postgres:12
    restart: on-failure
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      containers:
        ipv4_address: 172.19.0.10

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./:/usr/src/randomicu-fakedata
    - ./deploy/start.sh:/usr/src/randomicu-fakedata/start.sh
    depends_on:
      - database
    ports:
    - 8000:8000
    env_file:
      - .env
    networks:
      containers:
        ipv4_address: 172.19.0.20

volumes:
  database-data:

networks:
  containers:
    external:
      name: containers
