[tool.poetry]
name = "randomicu-fakedata"
version = "0.0.1"
description = ""
authors = ["pythoninja"]

[tool.poetry.dependencies]
python = "^3.8"
mimesis = "^4.1.2"
fastapi = "^0.61.1"
uvicorn = "^0.11.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
requests = "^2.24.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
