[tool.poetry]
name = "randomicu-fakedata"
version = "0.0.1"
description = "FastAPI backend for Random.icu Services"
authors = ["pythoninja"]

[tool.poetry.dependencies]
python = "^3.9"
mimesis = "^4.1.3"
fastapi = "^0.67.0"
uvicorn = {extras = ["standard"], version = "^0.14.0"}
asyncpg = "^0.23.0"
databases = {extras = ["postgresql"], version = "^0.4.2"}
SQLAlchemy = "^1.4.22"
python-dotenv = "^0.18.0"
gunicorn = "^20.1.0"
psycopg2 = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
requests = "^2.26.0"
pre-commit = "^2.13.0"
flake8 = "^3.9.2"
flake8-pytest-style = "^1.5.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-s"
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
