# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/randomicu/fakedata-provider"

[version]
current = "1.0.8"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore(release): v{new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "./app/__init__.py"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

  [[before_commit]]
  name = "Bump Poetry"
  cmd = "poetry version {new_version}"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
