name: ci
on:
  pull_request_target

permissions:
  packages: read

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_SERVER: localhost
          POSTGRES_DB: fakedata
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Add Python 3.9.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4

    - name: Add poetry 1.1.5
      uses: Gr1N/setup-poetry@v4
      with:
        poetry-version: 1.1.5

#    - name: Cache poetry's venv
#      uses: actions/cache@v2.1.2
#      id: cache
#      with:
#        path: ~/.virtualenvs
#        key: ${{ runner.os }}-cache-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-cache-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}

    - name: Set poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install Dependencies
      run: poetry add --dev pytest-cov && poetry install --no-root
#      if: steps.cache.outputs.cache-hit != 'true'

    - name: Run db migrations and pytest
      env:
        FAKEDATA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/fakedata
      run: |
        docker run --network host --rm --env "FAKEDATA_DATABASE_URL=$FAKEDATA_DATABASE_URL" ghcr.io/randomicu/fakedata-database:latest
        PYTHONPATH=$(pwd) poetry run pytest -vvv --cov .
